1) Manuel değerleri el ile girerek 3 boyutlu bir array oluşturup bir değişkene atayın. Ardından 3 boyutlu olup olmadığına bakmak için dimension'ını kontrol edin


In [ ]:
import numpy as np

In [ ]:
arr3D=np.array([[[1,1,1],[2,2,2],[3,3,3]],
                [[4,4,4],[5,5,5],[6,6,6]]
                ])
arr3D.ndim

3

2) 34, 40, 46, 52... 112 şeklinde devam eden 1 boyutlu bir array oluşturun.


In [ ]:
arr=np.arange(34,113,6)
arr

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

3) 50-500 arasında lineer artış gösteren 91 tane tam sayıdan oluşan bir array oluşturun.(dtype'ı int olsun)


In [ ]:
arrlinspace=np.linspace(50,500,91,dtype=int)
arrlinspace

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100, 105, 110,
       115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175,
       180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240,
       245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
       310, 315, 320, 325, 330, 335, 340, 345, 350, 355, 360, 365, 370,
       375, 380, 385, 390, 395, 400, 405, 410, 415, 420, 425, 430, 435,
       440, 445, 450, 455, 460, 465, 470, 475, 480, 485, 490, 495, 500])

4) 100(10**2) ile 10000(10**5) arasında logaritmik artış gösteren 8 sayıdan oluşan bir array oluşturun.


In [ ]:
arrLog=np.logspace(2,5,8)
arrLog

array([   100.        ,    268.26957953,    719.685673  ,   1930.69772888,
         5179.47467923,  13894.95494373,  37275.93720315, 100000.        ])

5) 0-8 tam arasındaki ardışık tam sayılardan oluşan(0 ve 8 dahil toplam 9 değer) 3x3 shape'inde bir matris oluşturun.


In [ ]:
arr3x3=np.random.randint(0,9,(3,3))
arr3x3

array([[8, 4, 2],
       [2, 7, 1],
       [3, 0, 3]])

6) 6x6 formatında bir sıfır matrisi oluşturun. (dtype'ı int olsun)


In [ ]:
arrZero6x6=np.zeros((6,6),dtype=int)
arrZero6x6.shape

(6, 6)

7) 4x4 formatında bir bir matrisi oluşturun. (dtype'ı int olsun)


In [ ]:
arrOnes4x4=np.ones((4,4),dtype=int)
arrOnes4x4

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

8) 8x8 formatında bir birim matris oluşturun. (Sadece sol köşegeni 1 geri kalan değerleri 0 olan matris'e birim matris deniyor.) (dtype'ı int olsun)


In [ ]:
arr8x8eye=np.eye(8,8,dtype=int)
arr8x8eye

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

9) 5x5 formatında bir köşegen matrisi oluşturun (Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün değerleri 0) (Bunu henüz görmediniz ama birim matrise benziyor, sadece köşegen değerleri 1 değil 3 olacak. Bir şeyler düşünün)


In [ ]:
arr5x5eye=np.eye(5,5,dtype=int)
arr5x5eye*3

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

10) np.random modülünden uygun fonksiyonu kullanarak 0-1 arasında toplam 6 tane değerden oluşan 1 boyutlu bir array oluşturun.


In [ ]:
arr01=np.random.rand(6)
arr01.shape

(6,)

11) np.random modülünden uygun fonksiyonu kullanarak 50-100 arasındaki(50 ve 100 dahil) tam sayılardan 10 tanesiyle oluşan (5,2) shape'inde bir array oluşturun. Ardından bu arrayin shape'ini kontrol edin.


In [ ]:
arr5x2=np.random.randint(50,101,(5,2))
arr5x2.shape

(5, 2)

12) np.random modülünden uygun fonksiyonu kullanarak 100-1000(1000 dahil değil) arasındaki tam sayılardan rastgele 50 tanesinden oluşan (2,5,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in dimension'ını(boyutunu) ve shape'ini kontrol edin.


In [ ]:
arr2x5x5=np.random.randint(100,1000,(2,5,5))
arr2x5x5

array([[[519, 314, 679, 388, 786],
        [127, 769, 359, 175, 485],
        [384, 790, 399, 176, 960],
        [461, 914, 168, 173, 464],
        [960, 453, 147, 742, 999]],

       [[400, 319, 178, 953, 955],
        [277, 215, 948, 635, 469],
        [233, 241, 172, 127, 138],
        [191, 717, 886, 843, 301],
        [839, 758, 279, 435, 622]]])

In [ ]:
arr2x5x5.shape

(2, 5, 5)

In [ ]:
arr2x5x5.ndim

3

13) np.random modülünden uygun fonksiyonu kullanarak 0-100(0 ve 100 dahil) arasındaki tam sayılardan 10 tane seçerek bir array oluşturun. Bu array'in maximum, mininmum değerlerine ve bu değerlerin indexlerine bakın.


In [ ]:
arr=np.random.randint(0,101,10)
arr

array([50, 43, 91, 29, 71, 40, 90, 56, 94, 21])

In [ ]:
arr.max()

94

In [ ]:
arr.argmax()

8

In [ ]:
arr.min()

21

In [ ]:
arr.argmin()

9

14) np.random modülünden uygun fonksiyonu kullanarak 300-500(300 ve 500 dahil) arasındaki tam sayılardan 20 tane seçerek (2,2,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in içindeki 20 tam sayı arasından maximum ve minimum değerleri manuel olarak tespit edin ve indexleme yaparak çekmeye çalışın.


In [ ]:
arr2x5x5=np.random.randint(300,501,(2,5,5))
arr2x5x5

array([[[328, 317, 328, 332, 373],
        [377, 463, 492, 307, 485],
        [349, 470, 430, 498, 324],
        [459, 440, 425, 496, 310],
        [454, 318, 349, 350, 335]],

       [[393, 384, 465, 391, 348],
        [303, 384, 363, 462, 418],
        [332, 362, 437, 405, 337],
        [386, 447, 489, 439, 385],
        [474, 436, 342, 475, 435]]])

In [ ]:
arr2x5x5.argmax()

13

In [ ]:
arr2x5x5.argmin()

30

In [ ]:
arr2x5x5[1][1][0]

303

In [ ]:
arr2x5x5[0][2][3]

498

15) 0-50(50 dahil) arasındaki ardışık tam sayılardan oluşan bir array oluşturun. Ardından bu arrayin 20. ve 35. indexleri arasındaki değerleri 500'e eşitleyin ve yeni oluşan array'i ekrana yazdırarak broadcasting işleminin yapılıp yapılmadığını test edin.

In [ ]:
arr050=np.arange(0,51,dtype=int)
arr050[20]=500
arr050[35]=500
arr050

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34, 500,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50])