In [1]:
import numpy as np
import pandas as pd

In [2]:
#1) 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.

In [4]:
arr=np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
arr15x2=arr.reshape(15,2)
arr15x2

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [7]:
arr15x2.shape

(15, 2)

In [8]:
arr15x2.ndim

2

In [9]:
#2) 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.

In [10]:
arrRandom=np.random.randint(0,100,60)
arrRandom

array([39, 45, 37, 90, 17, 87, 91, 39, 34, 82, 55, 43, 36, 72, 25, 53,  5,
       51, 37, 53, 78, 29,  6, 93,  5, 34, 81, 98, 32, 84,  9, 91, 70,  1,
       62, 72,  9, 90, 37, 41, 32, 33, 19, 11, 20, 23, 63, 71, 16,  8, 12,
       58, 79, 35,  1,  1, 68, 25, 59, 34])

In [11]:
arr3x4x5=arrRandom.reshape(3,4,5)
arr3x4x5

array([[[39, 45, 37, 90, 17],
        [87, 91, 39, 34, 82],
        [55, 43, 36, 72, 25],
        [53,  5, 51, 37, 53]],

       [[78, 29,  6, 93,  5],
        [34, 81, 98, 32, 84],
        [ 9, 91, 70,  1, 62],
        [72,  9, 90, 37, 41]],

       [[32, 33, 19, 11, 20],
        [23, 63, 71, 16,  8],
        [12, 58, 79, 35,  1],
        [ 1, 68, 25, 59, 34]]])

In [12]:
arr3x4x5.shape

(3, 4, 5)

In [13]:
arr3x4x5.ndim

3

In [14]:
#3) 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.

In [16]:
arr4x5=np.random.randint(0,21,(4,5))
arr4x5.ndim


2

In [19]:
arr1D=arr4x5.reshape(-1)
arr1D

array([14,  6, 12,  6, 15, 13,  2, 18, 10,  6,  9, 18, 10, 14,  0,  2, 14,
        1,  7, 16])

In [23]:
#4) İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.

In [27]:
arr2D=np.arange(12).reshape(3,4)

In [28]:
arr2D

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
for x in arr2D:
  for i in x:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [30]:
for i in np.nditer(arr2D):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [31]:
#5) 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve
   #1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun.
   #Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.

In [34]:
x=np.arange(5,31,5)
y=np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [36]:
x+y

array([ 6, 12, 18, 24, 30, 36])

In [37]:
x-y

array([ 4,  8, 12, 16, 20, 24])

In [38]:
x*y

array([  5,  20,  45,  80, 125, 180])

In [40]:
x/y

array([5., 5., 5., 5., 5., 5.])

In [41]:
#6) 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.

In [42]:
arr0100=np.random.randint(0,101,10)

In [45]:
arr0100.sum()

419

In [46]:
arr0100.mean()

41.9

In [47]:
arr0100.max()

69

In [48]:
arr0100.var()

302.89

In [49]:
arr0100.std()

17.403735231265728

In [50]:
#7) 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.

In [53]:
arr020=np.arange(0,20)
arr553=np.arange(500,531)

In [54]:
arr553

array([500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512,
       513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525,
       526, 527, 528, 529, 530])

In [57]:
arrConcatenate=np.concatenate([arr020,arr553], axis = 0)

In [58]:
arrConcatenate

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 501, 502, 503, 504, 505,
       506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518,
       519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

In [59]:
#8) 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.

In [60]:
arr1550=np.arange(15,51)
arr101=np.arange(10,101)
arrCon=np.concatenate([arr1550,arr101],axis=0)
arrCon[25]=888
arrCon[50]=888

In [61]:
arrCon

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39, 888,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23, 888,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [62]:
#9) 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.

In [63]:
arr8x5_1=np.arange(40).reshape(8,5)
arr8x5_2=np.arange(320,360).reshape(8,5)

In [67]:
np.concatenate([arr8x5_1,arr8x5_2],axis=0) #axis=0 oldugunda array in y ekseninde sonuna ekleme yapar. yani satir boyunca

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [320, 321, 322, 323, 324],
       [325, 326, 327, 328, 329],
       [330, 331, 332, 333, 334],
       [335, 336, 337, 338, 339],
       [340, 341, 342, 343, 344],
       [345, 346, 347, 348, 349],
       [350, 351, 352, 353, 354],
       [355, 356, 357, 358, 359]])

In [69]:
np.concatenate([arr8x5_1,arr8x5_2],axis=1) # axis=1 oldugunda array in X ekseninde sonuna ekleme yapar. yani sutun boyunca

array([[  0,   1,   2,   3,   4, 320, 321, 322, 323, 324],
       [  5,   6,   7,   8,   9, 325, 326, 327, 328, 329],
       [ 10,  11,  12,  13,  14, 330, 331, 332, 333, 334],
       [ 15,  16,  17,  18,  19, 335, 336, 337, 338, 339],
       [ 20,  21,  22,  23,  24, 340, 341, 342, 343, 344],
       [ 25,  26,  27,  28,  29, 345, 346, 347, 348, 349],
       [ 30,  31,  32,  33,  34, 350, 351, 352, 353, 354],
       [ 35,  36,  37,  38,  39, 355, 356, 357, 358, 359]])

In [70]:
#10) 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.

In [73]:
np.concatenate([arr8x5_1,arr8x5_2],axis=2)

AxisError: ignored

In [74]:
np.stack([arr8x5_1,arr8x5_2],axis=2)

array([[[  0, 320],
        [  1, 321],
        [  2, 322],
        [  3, 323],
        [  4, 324]],

       [[  5, 325],
        [  6, 326],
        [  7, 327],
        [  8, 328],
        [  9, 329]],

       [[ 10, 330],
        [ 11, 331],
        [ 12, 332],
        [ 13, 333],
        [ 14, 334]],

       [[ 15, 335],
        [ 16, 336],
        [ 17, 337],
        [ 18, 338],
        [ 19, 339]],

       [[ 20, 340],
        [ 21, 341],
        [ 22, 342],
        [ 23, 343],
        [ 24, 344]],

       [[ 25, 345],
        [ 26, 346],
        [ 27, 347],
        [ 28, 348],
        [ 29, 349]],

       [[ 30, 350],
        [ 31, 351],
        [ 32, 352],
        [ 33, 353],
        [ 34, 354]],

       [[ 35, 355],
        [ 36, 356],
        [ 37, 357],
        [ 38, 358],
        [ 39, 359]]])

In [75]:
#11) [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.

In [81]:
arr=np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])

In [83]:
np.where(arr==5)

(array([ 5, 13]),)

In [84]:
#12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.

In [85]:
np.where(arr%2==0)

(array([ 1,  3,  4,  6,  7,  9, 11]),)

In [86]:
#13) Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.

In [88]:
np.where(arr>4)

(array([ 1,  2,  5,  9, 10, 11, 13]),)

In [89]:
#14) Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.

In [90]:
np.where(arr%5==0)

(array([ 1,  2,  5, 13]),)

In [91]:
#15) 85-100(100 dahil) arasından rastgele 1 tam sayı seçin


In [100]:
x=np.random.randint(85,100,1)
x

array([85])

In [101]:
#16) İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.

In [102]:
arr3x3=np.random.randint(10,100,(3,3))
arr3x3

array([[77, 25, 56],
       [63, 88, 32],
       [83, 13, 19]])

In [103]:
#17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.

In [107]:
np.random.choice(np.arange(35,61),1)

array([42])

In [108]:
#18) Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.

In [109]:
arr=np.array([3, 8, 10, 53])
arr

array([ 3,  8, 10, 53])

In [110]:
arr2x5=np.random.choice(arr,(2,5))
arr2x5

array([[53,  3,  8, 53,  3],
       [53,  3, 53, 10,  8]])

In [111]:
arr2x5.shape

(2, 5)

In [112]:
arr2x5.ndim

2